/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: test.html
Story format: Harlowe
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Harlowe;

public partial class @test: Cradle.StoryFormats.Harlowe.HarloweStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------

	public readonly Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros macros1;

	@test()
	{
		this.StartPassage = "c1";

		base.Vars = new VarDefs() { Story = this, StrictMode = true };

		macros1 = new Cradle.StoryFormats.Harlowe.HarloweRuntimeMacros() { Story = this };

		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: c1

	void passage1_Init()
	{
		this.Passages[@"c1"] = new StoryPassage(@"c1", new string[]{ "START", }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text("Bonjour Carl");
		yield return lineBreak();
		yield return text("Comment vas-tu ?");
		yield return lineBreak();
		yield return link("ça va bien et toi ?", "ça va bien et toi ?", null);
		yield return lineBreak();
		yield return link("ça roule", "ça roule", null);
		yield break;
	}


	// .............
	// #2: ça va bien et toi ?

	void passage2_Init()
	{
		this.Passages[@"ça va bien et toi ?"] = new StoryPassage(@"ça va bien et toi ?", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text("tranquille bg");
		yield break;
	}


	// .............
	// #3: ça roule

	void passage3_Init()
	{
		this.Passages[@"ça roule"] = new StoryPassage(@"ça roule", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text("bloque moi");
		yield break;
	}


}